[[customizations.filesystem]]
mountpoint = "/boot"
minsize = "512 MiB"
filesystem = "ext4"

[[customizations.filesystem]]
mountpoint = "/"
minsize = "15 GiB"
filesystem = "xfs"

[kernel]
cmdline = "ignition.firstboot ignition.platform.id=qemu"
